import { promises as fs } from 'node:fs';
import path from 'node:path';
import { PostgresAdapter, snapshotSchema } from '@stratum/database';
import type { ColumnInfo, TableInfo } from '@stratum/shared';
import { loadProject, resolveDatabaseUrl } from '../project.js';
import { fail, ok } from '../ui.js';

function pgTypeToTs(col: ColumnInfo): string {
  const t = col.dataType.toLowerCase();
  const u = col.udtName.toLowerCase();
  let base: string;
  if (t === 'boolean') base = 'boolean';
  else if (['smallint', 'integer', 'bigint', 'real', 'double precision', 'serial', 'bigserial', 'smallserial'].includes(t)) {
    base = 'number';
  } else if (['numeric', 'decimal', 'text', 'varchar', 'char', 'character varying', 'character', 'uuid', 'date', 'time', 'timetz', 'timestamp', 'timestamptz', 'inet', 'bytea'].includes(t)) {
    base = 'string';
  } else if (['json', 'jsonb'].includes(t)) {
    base = 'Record<string, unknown> | unknown[] | string | number | boolean | null';
  } else if (t === 'array' || u.startsWith('_')) {
    base = 'unknown[]';
  } else {
    base = 'unknown';
  }
  return col.nullable ? `${base} | null` : base;
}

function renderTableType(t: TableInfo): string {
  const rowFields = t.columns.map((c) => `        ${c.name}: ${pgTypeToTs(c)};`).join('\n');
  const insertFields = t.columns
    .map((c) => {
      const optional = c.nullable || c.defaultValue !== null;
      return `        ${c.name}${optional ? '?' : ''}: ${pgTypeToTs(c)};`;
    })
    .join('\n');
  const updateFields = t.columns.map((c) => `        ${c.name}?: ${pgTypeToTs(c)};`).join('\n');

  return `      ${t.name}: {
        Row: {
${rowFields}
        };
        Insert: {
${insertFields}
        };
        Update: {
${updateFields}
        };
      };`;
}

export async function typesGenerate(opts: { output: string; schema: string }): Promise<void> {
  const project = await loadProject();
  if (!project) fail('No stratum.json found.', 'Run `stratum init` first.');

  const url = await resolveDatabaseUrl(project.root);
  if (!url) fail('DATABASE_URL is not set.');

  const db = new PostgresAdapter({ connectionString: url, applicationName: 'stratum-cli' });
  try {
    const snapshot = await snapshotSchema(db, opts.schema);
    const tables = snapshot.tables.filter((t) => t.schema === opts.schema);

    const content = `// Generated by \`stratum types generate\`. Do not edit by hand.
// Source schema: ${opts.schema} · generated ${snapshot.generatedAt}

export interface Database {
  ${opts.schema}: {
    Tables: {
${tables.map(renderTableType).join('\n')}
    };
  };
}
`;

    const outPath = path.resolve(project.root, opts.output);
    await fs.writeFile(outPath, content);
    ok(`Wrote types for ${tables.length} table(s) to ${path.relative(process.cwd(), outPath)}`);
  } finally {
    await db.close();
  }
}
